### ISSUE TITLE
EN627 chl niskin_other_method incorrectly applied to some samples

### ISSUE THREAD

**Issue by ecrockford** [WHOIGit/nes-lter-chl-transect#13]
Is niskin_other_method variable a coded application? In EN627, Sosik and Rynearson method chl's of the following cast/niskin have values in niskin_other_method when I believe that should be NA. 

C8N8         (says 9/10/11 but should only be N8)
C12N10     (says 11/12 but should only be N10)
C19N9       (says 11/12 but should only be N9)
C24N9       (says 11/12 but should only be N9)

**Comment by katemorkeski** [comment]
eliminated niskin_other_method
