### ISSUE TITLE
next version: migrate to the utilities package

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-chl-transect#8]
deprecate (i.e., not use anymore) edi-utilities.R

**Comment by joannekoch** [comment]
Delete the local copy of edi-utilites.R.  Replace the call to xlsx_to_template with excel_to_template. Migrate the following  function calls to the utilities package: data_coverage, map_locs, project_insert, read_from_api. Note that entityName_check is not used.

**Comment by joannekoch** [comment]
At the time of this migration, the file NES-LETER-chla-T0-SMD.csv had a column number mismatch with the other SMD files in the directory. 

To workaround the problem, the following temporary change was made to chl-transect-eml-assembly.RMD to skip reading in NES-LETER-chla-T0-SMD.csv:
files <- Sys.glob("*SMD*.csv")  
files <- Sys.glob("en*SMD*.csv")
